language: php

php:
  - 7.1

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer install --prefer-source

script:
  - ./vendor/bin/phpunit

notifications:
  email: false